# Generated by Django 5.2.1 on 2025-08-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dna_storage_request', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='dnaaliquot',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='requester',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tissue',
            options={'managed': True},
        ),
    ]
