# Generated by Django 5.2.1 on 2025-08-25 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_storage_request', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tissue',
            name='update_at',
        ),
        migrations.AddField(
            model_name='dnaaliquot',
            name='metadata',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dna_storage_request.metadata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnaaliquot',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dna_storage_request.request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnaaliquot',
            name='shipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dna_storage_request.shipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadata',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dna_storage_request.request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dna_storage_request.requester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requester',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requester_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dna_storage_request.request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissue',
            name='metadata',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dna_storage_request.metadata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissue',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dna_storage_request.request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissue',
            name='shipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dna_storage_request.shipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dnaaliquot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dnaaliquot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requester',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requester',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tissue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
