# Generated by Django 5.2.1 on 2025-08-28 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_storage_request', '0003_remove_tissue_update_at_dnaaliquot_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='contact_person_email',
            field=models.EmailField(help_text='Email de contacto del requester', max_length=100, validators=[django.core.validators.EmailValidator(message='Ingrese un email válido')]),
        ),
        migrations.AlterField(
            model_name='requester',
            name='first_name',
            field=models.CharField(help_text='Nombre del requester', max_length=100),
        ),
        migrations.AlterField(
            model_name='requester',
            name='institution_location',
            field=models.CharField(help_text='Ej: Bogotá, Colombia o Berlin, Germassssny', max_length=100),
        ),
        migrations.AlterField(
            model_name='requester',
            name='last_name',
            field=models.CharField(help_text='Apellido del requester', max_length=100),
        ),
        migrations.AlterField(
            model_name='requester',
            name='requester_institution',
            field=models.CharField(help_text='Ej: Universidad Nacional de Colombia, Max Planck Institutes', max_length=100),
        ),
    ]
