# Generated by Django 5.2.1 on 2025-09-02 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_storage_request', '0004_alter_requester_contact_person_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnaaliquot',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dna_storage_request.shipment'),
        ),
        migrations.AlterField(
            model_name='requester',
            name='institution_location',
            field=models.CharField(help_text='Ej: Bogotá, Colombia o Berlin, Germany', max_length=100),
        ),
        migrations.AlterField(
            model_name='tissue',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dna_storage_request.shipment'),
        ),
    ]
