# Generated by Django 5.2.1 on 2025-09-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_storage_request', '0005_alter_dnaaliquot_shipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tissue',
            name='is_in_jacq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tissue',
            name='tissue_barcode',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tissue',
            name='tissue_sample_storage_location',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
